# Utilise l'image officielle de Node.js
FROM node:20

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json (si existants)
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du projet
COPY . .

# Exposer le port utilisé par ton application React/Vue/Angular (ex: 3000 pour React)
EXPOSE 5173

# Lancer l'application (modifie selon ton framework)
CMD ["npm", "run","dev"]
