#Use the official Redis image from Docker Hub
FROM redis:latest

#Copy a custom Redis configuration file
COPY ./src/main/java/com/example/gamestate/config/redis.conf /etc/redis/redis.conf
RUN chmod 777 /etc/redis/redis.conf

#Expose the default Redis port
EXPOSE 6379

#Run Redis with the custom configuration file
CMD ["redis-server", "/etc/redis/redis.conf"]